repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.21
    hooks:
      # Update the requirements.txt if pyproject.toml changes
      - id: uv-export
        args: ["--frozen", "--output-file=requirements.txt", "--quiet"]
